In [ ]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sea
arr=np.array([1,2,3,4])
print(arr)
print(arr.ndim)
print(arr[0,3])
arr1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr1[1, 1, 0])

[[1 2 3 4]]
2
4
7


In [21]:
arr2 = np.array([1,2,3,4,5,6,7])
print(arr2[4:])
print(arr2[0:5:2])

[5 6 7]
[1 3 5]


In [22]:
import numpy as np

arr3 = np.array([1.1, 2.1, 3.1])

newarr = arr3.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [23]:
import numpy as np
arr4 = np.array([-1, 0, 1])
newarr = arr4.astype(bool)
print(newarr)

[ True False  True]


In [36]:
arr5=np.array([1,2,3,4,5])
x = arr5.copy()
arr5[0]=56
print(arr5)
print(x)

[56  2  3  4  5]
[1 2 3 4 5]


In [26]:
x

array([[1, 2, 3, 4]])

In [37]:
x=arr5.view()
arr[0] = 42
print(arr5)
print(x)


[56  2  3  4  5]
[56  2  3  4  5]


In [41]:
arr6= np.array([1,2,3,4,5,6])
x = arr6.copy()
y = arr6.view()
print(x.base)
print(y.base)


None
[1 2 3 4 5 6]
